# Generated by Django 5.0.6 on 2024-07-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('id_documento', models.CharField(max_length=255)),
                ('nombre_documento', models.CharField(max_length=255)),
                ('hh_vendidas', models.IntegerField()),
                ('hh_gastadas', models.IntegerField()),
                ('dinero_invertido', models.FloatField()),
                ('dinero_gastado', models.FloatField()),
                ('estado_proyecto', models.CharField(max_length=255)),
                ('hh_ganadas', models.IntegerField()),
                ('eficiencia_hh', models.FloatField()),
                ('eficiencia_dinero', models.FloatField()),
                ('eficacia', models.FloatField()),
            ],
        ),
    ]
