# Generated by Django 5.0.6 on 2024-07-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=100)),
                ('id_documento', models.CharField(max_length=100)),
                ('nombre_documento', models.CharField(max_length=100)),
                ('hh_vendidas', models.IntegerField()),
                ('dinero_invertido', models.FloatField()),
                ('dinero_gastado', models.FloatField(default=0)),
                ('estado_proyecto', models.CharField(default='Rev0', max_length=50)),
                ('hh_gastadas', models.IntegerField(default=0)),
                ('hh_ganadas', models.IntegerField(default=0)),
                ('eficiencia_hh', models.FloatField(default=0)),
                ('eficiencia_dinero', models.FloatField(default=0)),
                ('eficacia', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
